import shutil
from setuptools import setup, Command


class CleanCommand(Command):
    """Custom clean command to remove build, dist and egg-info folders."""
    user_options = []
    description = (
        "Custom clean command to remove build, dist and egg-info folders."
    )

    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    @staticmethod
    def run():
        """Clean directories generated by the install command."""
        print("Cleaning build, dist and egg-info directories.")
        try:
            shutil.rmtree("build")
        except FileNotFoundError:
            pass

        try:
            shutil.rmtree("dist")
        except FileNotFoundError:
            pass

        try:
            shutil.rmtree("cookiecutter_cli.egg-info")
        except FileNotFoundError:
            pass

        print("Cleaning done !")


setup(
    name='cookiecutter-cli',
    version='0.1.0',
    author='Kalwyn Solork',
    description='Cookiecutter template for python command line interface.',
    author_email='kalwyn.protonmail.com',
    license='MIT',
    url='https://github.com/Kalwyn/cookiecutter-cli',
    keywords=['cookiecutter', 'template', 'cli'],
    classifiers=[
        'Environment :: Console',
        'Natural Language :: English',
        'Topic :: Software Development',
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Programming Language :: Python :: 3 :: Only',
        "License :: OSI Approved :: MIT License",
    ],
    cmdclass={
        'clean': CleanCommand,
    }
)
